#!name=清理脚本 - 清空存储数据
#!author=Linsar
#!date=2026-04-22
#!desc=清空 PingMe 和 WeTalk 的旧存储数据，重新开始

[Script]
clear = type=cron, cronexp="0 0 * * *", script-path=https://raw.githubusercontent.com/Linsars/Surge/main/JS/clear-storage.js, timeout=120

[MITM]
