#!name=诊断脚本 - 检查存储数据
#!author=Linsar
#!date=2026-04-22
#!desc=检查 PingMe 和 WeTalk 的存储数据格式

[Script]
diagnose = type=cron, cronexp="0 0 * * *", script-path=https://raw.githubusercontent.com/Linsars/Surge/main/JS/diagnose.js, timeout=120

[MITM]
